### ISSUE TITLE
`invalid_grant` failures under Python3

### ISSUE THREAD

**Issue by tseaver** [google/oauth2client#125]
When running with the branch from https://github.com/GoogleCloudPlatform/gcloud-python/pull/580:

```python
$ .tox/regression3/bin/python regression/run_regression.py --package=storage
ERROR

======================================================================
ERROR: setUpModule (storage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/regression/storage.py", line 42, in setUpModule
    SHARED_BUCKETS['test_bucket'] = CONNECTION.create_bucket(bucket_name)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/regression3/lib/python3.4/site-packages/gcloud/storage/connection.py", line 351, in create_bucket
    data={'name': bucket.name})
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/regression3/lib/python3.4/site-packages/gcloud/storage/connection.py", line 239, in api_request
    method=method, url=url, data=data, content_type=content_type)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/regression3/lib/python3.4/site-packages/gcloud/storage/connection.py", line 176, in make_request
    body=data)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/regression3/lib/python3.4/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/regression3/lib/python3.4/site-packages/oauth2client/client.py", line 530, in new_request
    self._refresh(request_orig)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/regression3/lib/python3.4/site-packages/oauth2client/client.py", line 744, in _refresh
    self._do_refresh_request(http_request)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/regression3/lib/python3.4/site-packages/oauth2client/client.py", line 807, in _do_refresh_request
    raise AccessTokenRefreshError(error_msg)
oauth2client.client.AccessTokenRefreshError: invalid_grant

----------------------------------------------------------------------
```

- Those tests use the `GOOGLE_APPLICATION_CREDENTIALS` envvar, and run fine under Python2.

- All `gcloud-python` unit tests pass on that branch under Python2 and Python3.

**Comment by craigcitro** [comment]
cc @anthmgoogle

**Comment by dhermes** [comment]
It's a formatting issue of bytes vs. string.

In Python2:

```python
>>> body
'assertion=eyJ...'
```

In Python3:

```python
>>> body
'assertion=b%22b%27eyJ...'
```

**Comment by dhermes** [comment]
@craigcitro Can you assign this issue to me? I am working on it.

**Comment by craigcitro** [comment]
@dhermes it won't let me *assign* to anyone outside our org, unfortunately.
