### ISSUE TITLE
Installing via pip fails (404 DistributionNotFound error)

### ISSUE THREAD

**Issue by kylegoetz** [google/oauth2client#147]
Howto says to run "pip install oath2client" and here is the output when I do so:

Downloading/unpacking oath2client
  Getting page https://pypi.python.org/simple/oath2client/
  Could not fetch URL https://pypi.python.org/simple/oath2client/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/oath2client/ when looking for download links for oath2client
  Getting page https://pypi.python.org/simple/
  URLs to search for versions for oath2client:
  * https://pypi.python.org/simple/oath2client/
  Getting page https://pypi.python.org/simple/oath2client/
  Could not fetch URL https://pypi.python.org/simple/oath2client/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/oath2client/ when looking for download links for oath2client
  Could not find any downloads that satisfy the requirement oath2client
Cleaning up...
No distributions at all found for oath2client
Exception information:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
pip.exceptions.DistributionNotFound: No distributions at all found for oath2client

pip search oath also reveals there is no oath2client

**Comment by kylegoetz** [comment]
Whoops, had a typo in package name.
