### ISSUE TITLE
More userfriendly error message, not just "No crypto library available"

### ISSUE THREAD

**Issue by defuz** [google/oauth2client#160]
Guys, could you create a little more understandable (not only telepath) error message:

```
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/python/request_handler.py", line 225, in handle_interactive_request
    exec(compiled_code, self._command_globals)
  File "<string>", line 9, in <module>
  File "/Users/defuz/Projects/playscape/PublishingKit_Backend/main.py", line 18, in <module>
    app = make_app()
  File "/Users/defuz/Projects/playscape/PublishingKit_Backend/main.py", line 11, in make_app
    app.traffic = TrafficService()
  File "/Users/defuz/Projects/playscape/PublishingKit_Backend/models/traffic.py", line 70, in __init__
    scope='https://www.googleapis.com/auth/bigquery')
  File "/Users/defuz/Projects/playscape/PublishingKit_Backend/libraries/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/defuz/Projects/playscape/PublishingKit_Backend/libraries/oauth2client/client.py", line 1458, in __init__
    _RequireCryptoOrDie()
  File "/Users/defuz/Projects/playscape/PublishingKit_Backend/libraries/oauth2client/client.py", line 1412, in _RequireCryptoOrDie
    raise CryptoUnavailableError('No crypto library available')
CryptoUnavailableError: No crypto library available
```

What do you think I should do after receiving this error message?

**Comment by anthmgoogle** [comment]
defuz@, this is happening because you are loading a .p12 file which is format PCKS#12, which requires a special C crypto library that is not installed by default and is hard to track down. It is agreed that this is a serious usability problem that we have been working on with a new solution.

There are a few options to unblock you. You can locate the the C crypto library, but this is relatively hard.

The simpler solution would be to download the new JSON format of service account from the Cloud Console, and use it by using either GoogleCredentials.get_application_default or GoogleCredentials.from_stream to load it. This new format combines the email address and the PKCS#8 format which oauth2client can read without any other packages. See:
https://developers.google.com/identity/protocols/application-default-credentials

In terms of this specific issue, it is definitely still an unhelpful error message. It could be improved to refer to this new feature as the solution.

**Comment by theacodes** [comment]
Thank you for creating this issue, however, this project is deprecatedand we will only be addressing critical security issues. You can read moreabout this deprecation [here](http://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html).

If you need support or help using this library, we recommend that you ask yourquestion on StackOverflow.

If you still think this issue is relevant and should be addressed, pleasecomment and let us know!
