### ISSUE TITLE
Clean_headers is broken in python 3

### ISSUE THREAD

**Issue by JelteF** [google/oauth2client#163]
```
Traceback (most recent call last):
  File "/home/jelte/fun/viaduct/viaduct/api/google.py", line 35, in build_service
    return build(service_type, api_version, http=http)
  File "/home/jelte/fun/viaduct/venv/lib/python3.4/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/jelte/fun/viaduct/venv/lib/python3.4/site-packages/googleapiclient/discovery.py", line 196, in build
    resp, content = http.request(requested_url)
  File "/home/jelte/fun/viaduct/venv/lib/python3.4/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/jelte/fun/viaduct/venv/lib/python3.4/site-packages/oauth2client/client.py", line 560, in new_request
    resp, content = request_orig(*args)
  File "/home/jelte/fun/viaduct/venv/lib/python3.4/site-packages/httplib2/__init__.py", line 1139, in request
    headers = self._normalize_headers(headers)
  File "/home/jelte/fun/viaduct/venv/lib/python3.4/site-packages/httplib2/__init__.py", line 1107, in _normalize_headers
    return _normalize_headers(headers)
  File "/home/jelte/fun/viaduct/venv/lib/python3.4/site-packages/httplib2/__init__.py", line 195, in _normalize_headers
    return dict([ (key.lower(), NORMALIZE_SPACE.sub(value, ' ').strip())  for (key, value) in headers.items()])
  File "/home/jelte/fun/viaduct/venv/lib/python3.4/site-packages/httplib2/__init__.py", line 195, in <listcomp>
    return dict([ (key.lower(), NORMALIZE_SPACE.sub(value, ' ').strip())  for (key, value) in headers.items()])
```

I'm getting this traceback because cleanheaders doesn't converts strings to bytes and httplib2 can't handle those.

The code in question is this:
```python
    for k, v in six.iteritems(headers):
      clean_k = k if isinstance(k, bytes) else str(k).encode('ascii')
      clean_v = v if isinstance(v, bytes) else str(v).encode('ascii')

      clean[clean_k] = clean_v
```

for me it works when I just remove that code, but I guess it is for python 2 problems.

I don't mind making a pull request, it's just that I a quite unsure what the lines are supposed to do since in python 3 concatenating strings will always make a valid string again.

**Comment by dhermes** [comment]
This is certainly fixed in the latest version.

```python
>>> import sys
>>> sys.version
'3.4.0 (default, Apr 11 2014, 13:05:11) \n[GCC 4.8.2]'
>>> import oauth2client
>>> oauth2client.__version__
'1.4.11'
>>> from oauth2client.client import clean_headers
>>> clean_headers({'a': 'b'})
{b'a': b'b'}
```

Please re-open if you are still having issues.
