### ISSUE TITLE
Intermittent devshell test failures

### ISSUE THREAD

**Issue by craigcitro** [google/oauth2client#188]
from time to time, i've started seeing `devshell`-related test failures, like this:

```
[~/gh/oauth2client] {master} $ tox -e py27
GLOB sdist-make: /Users/craigcitro/gh/oauth2client/setup.py
py27 inst-nodeps: /Users/craigcitro/gh/oauth2client/.tox/dist/oauth2client-1.4.11.zip
py27 runtests: PYTHONHASHSEED='1896158765'
py27 runtests: commands[0] | nosetests --ignore-files=test_appengine\.py
.........EException in thread Thread-1:
Traceback (most recent call last):
  File "/Users/craigcitro/ext/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/craigcitro/gh/oauth2client/tests/test_devshell.py", line 63, in run
    resp_1 = s.recv(6).decode()
error: [Errno 35] Resource temporarily unavailable

...................................................................................................................................................................
======================================================================
ERROR: test_handles_ignores_extra_fields (tests.test_devshell.DevshellCredentialsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/craigcitro/gh/oauth2client/tests/test_devshell.py", line 122, in test_handles_ignores_extra_fields
    creds = DevshellCredentials()
  File "/Users/craigcitro/gh/oauth2client/oauth2client/devshell.py", line 113, in __init__
    self._refresh(None)
  File "/Users/craigcitro/gh/oauth2client/oauth2client/devshell.py", line 116, in _refresh
    self.devshell_response = _SendRecv()
  File "/Users/craigcitro/gh/oauth2client/oauth2client/devshell.py", line 83, in _SendRecv
    raise CommunicationError('saw no newline in the first 6 bytes')
CommunicationError: saw no newline in the first 6 bytes

----------------------------------------------------------------------
Ran 173 tests in 11.581s

FAILED (errors=1)
ERROR: InvocationError: '/Users/craigcitro/gh/oauth2client/.tox/py27/bin/nosetests --ignore-files=test_appengine\\.py'
________________________________________ summary ________________________________________
ERROR:   py27: commands failed
```

it's not consistent -- something is flaky. @aalexand does this look familiar?

**Comment by aalexand** [comment]
I haven't seen this, but I'll take a look.

**Comment by aalexand** [comment]
Is this local or Jenkins runs or both?

**Comment by craigcitro** [comment]
1. i've only seen it locally on my mac. (maybe it's OSX-specific?)
2. haven't seen it on travis; we don't have a jenkins setup.
