### ISSUE TITLE
oauth2client.appengine module docs are not being built

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#289]
See: http://oauth2client.readthedocs.org/en/latest/source/oauth2client.appengine.html

![screen_shot_001](https://cloud.githubusercontent.com/assets/520669/9482087/17db6490-4b45-11e5-8a9a-6191180a19ed.png)

---

I have a [hack][1] in place to make this work, but it doesn't seem to be sufficient. (I swear it used to work :grinning: )

[1]: https://github.com/google/oauth2client/blob/f29c164b9196da8365f210dde0226d6527c6d30f/docs/conf.py#L50-L67

**Comment by dhermes** [comment]
Looking in a build: https://readthedocs.org/projects/oauth2client/builds/3273352/

The line

```
python /home/docs/checkouts/readthedocs.org/user_builds/oauth2client/envs/latest/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
```

has an `ImportError`

```python
/home/docs/checkouts/readthedocs.org/user_builds/oauth2client/checkouts/latest/docs/source/oauth2client.appengine.rst:4: WARNING: autodoc: failed to import module u'oauth2client.appengine'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/oauth2client/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oauth2client/checkouts/latest/oauth2client/appengine.py", line 30, in <module>
    from google.appengine.api import app_identity
ImportError: No module named google.appengine.api
looking for now-outdated files... none found
```

**Comment by dhermes** [comment]
This isn't true anymore. It fixed itself!
