### ISSUE TITLE
clientsecrets._loadfile hides native OSError

### ISSUE THREAD

**Issue by seanttierney** [google/oauth2client#348]
Native error messages are masked by the InvalidClientSecrets error. _loadfile naively assumes all OSErrors are the result of missing file. Permission issues present as missing file issues and can be rather frustrating to diagnose.

**Comment by dhermes** [comment]
Thanks @seanttierney!

**Comment by dhermes** [comment]
Can you provide a stacktrace?

**Comment by dhermes** [comment]
It seems the issue comes from [a file `open`][1]:

```python
    try:
        with open(filename, 'r') as fp:
            obj = json.load(fp)
    except IOError:
        raise InvalidClientSecretsError('File not found: "%s"' % filename)
```

It's also unclear to me why `"%s"` was used instead of `%r`.

[1]: https://github.com/google/oauth2client/blob/4cf98dc4c4988b9a30d236802f1ae4289f1e631f/oauth2client/clientsecrets.py#L120-L125

**Comment by seanttierney** [comment]
I found the error as part of log data my for my service stack, so the following is not a clean interpreter trace. So I'll need to extract out a workable example. My services run as non-root. The client secrets file didn't have read permission for the given users.
```bash
$ service google-service start
.... output...crash
  File "/path/to/local/lib/python2.7/site-packages/oauth2client/clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "/path/to/local/lib/python2.7/site-packages/oauth2client/clientsecrets.py", line 125, in _loadfile
    raise InvalidClientSecretsError('File not found: "%s"' % filename) 
oauth2client.clientsecrets.InvalidClientSecretsError: File not found: "/path/to/client_secrets.json
```
from the terminal
```bash
$ ls -la /path/to/client_secrets
-rw------- 1 root root xxx Dec 1 xx:xx /path/to/client_secrets.json
$ chmod +r /path/to/client_secrets.json
$ ls -la /path/to/client_secrets
-rw-r--r-- 1 root root xxx Dec 1 xx:xx /path/to/client_secrets.json
$ service google-service start
.... output...no crash
^-Ctl
$ chmod 0600 /path/to/client_secrets.json
-rw------- 1 root root xxx Dec 1 xx:xx /path/to/client_secrets.json
$ service google-service start
.... output...crash 
  File "/path/to/local/lib/python2.7/site-packages/oauth2client/clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "/path/to/local/lib/python2.7/site-packages/oauth2client/clientsecrets.py", line 125, in _loadfile
    raise InvalidClientSecretsError('File not found: "%s"' % filename) 
oauth2client.clientsecrets.InvalidClientSecretsError: File not found: "/path/to/client_secrets.json
```

I can get you a better stack from python terminal if you need, but it will be awhile.
```python
#here's the relevant code from clientsecrets.py
def _loadfile(filename):
    try:
        with open(filename, 'r') as fp:
            obj = json.load(fp)
    except IOError:
        raise InvalidClientSecretsError('File not found: "%s"' % filename)
    return _validate_clientsecrets(obj)
```

**Comment by dhermes** [comment]
No worries, I just wanted the stack-trace to pinpoint where the error happened.

I'm actually surprised `IOError` catches the errors from `open()`. I thought it was an `OSError` and

```python
>>> OSError.__bases__
(<type 'exceptions.EnvironmentError'>,)
>>> IOError.__bases__
(<type 'exceptions.EnvironmentError'>,)
```

**Comment by dhermes** [comment]
```
$ cat <<EOF > g.py
> with open('a.txt', 'rb') as fh:
>     print fh.read().strip()
> EOF
$ python g.py
Traceback (most recent call last):
  File "g.py", line 1, in <module>
    with open('a.txt', 'rb') as fh:
IOError: [Errno 2] No such file or directory: 'a.txt'
$ echo Foo > a.txt
$ python g.py
Foo
$ ls -alFG a.txt
-rw-rw-r-- 1 dhermes 4 Dec  1 16:20 a.txt
$ sudo chown root a.txt
$ sudo chmod 600 a.txt
$ ls -alFG a.txt
-rw------- 1 root 4 Dec  1 16:20 a.txt
$ python g.py
Traceback (most recent call last):
  File "g.py", line 1, in <module>
    with open('a.txt', 'rb') as fh:
IOError: [Errno 13] Permission denied: 'a.txt'
```

**Comment by seanttierney** [comment]
Nice! You beat me to it.
