### ISSUE TITLE
Fix flaky test_verify_id_token_bad_tokens failure

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#405]
This recently caused a "broken" [build][1] (though I restarted it)

```python
======================================================================
FAIL: test_verify_id_token_bad_tokens (tests.test_jwt.PEMCryptTestsOpenSSL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/google/oauth2client/tests/test_jwt.py", line 181, in test_verify_id_token_bad_tokens
    self._check_jwt_failure(jwt, 'Token used too early')
  File "/home/travis/build/google/oauth2client/tests/test_jwt.py", line 94, in _check_jwt_failure
    self.assertTrue(expected_error in str(exc_manager.exception))
nose.proxy.AssertionError: False is not true
-------------------- >> begin captured logging << --------------------
oauth2client.crypt: DEBUG: ... REDACTED ...
oauth2client.crypt: DEBUG: ... REDACTED ...
oauth2client.crypt: DEBUG: ... REDACTED ...
--------------------- >> end captured logging << ---------------------
```

[1]: https://travis-ci.org/google/oauth2client/builds/108176722

**Comment by dhermes** [comment]
I captured this locally and the error is

```python
AppIdentityError('Invalid token signature',)
```

**Comment by dhermes** [comment]
Issue [found][1]! We are stripping off the byte `=` from signed bytes. It seems the code got confused about what was bytes and what was base64. Eek.

[1]: https://github.com/google/oauth2client/blob/b13ab40a01adacf0075fd52f95173abb33297254/oauth2client/crypt.py#L97
