### ISSUE TITLE
ImportError: No module named locked_file

### ISSUE THREAD

**Issue by smythp** [google/oauth2client#414]
Got the following output when connecting to the calendar API. Had to copy locked_file.py from contrib to the oauth2client folder to resolve the error output.

```
WARNING:root:No module named locked_file
Traceback (most recent call last):
  File "/home/patrick/.pyenv/versions/calendar/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 38, in autodetect
    from . import file_cache
  File "/home/patrick/.pyenv/versions/calendar/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 32, in <module>
    from oauth2client.locked_file import LockedFile
ImportError: No module named locked_file
```

**Comment by dhermes** [comment]
This is an issue with `google-api-python-client` as it is using an old import path.

**Comment by smythp** [comment]
Thanks for the response and for the resource.
