### ISSUE TITLE
httplib2 dependency needs to be updated to latest version

### ISSUE THREAD

**Issue by tswast** [google/oauth2client#441]
I ran into https://github.com/google/google-api-python-client/issues/135 today when testing https://github.com/GoogleCloudPlatform/cloud-vision/pull/28. Pip installed an old version of httplib2 when I installed the google-api-client-python (and recursively oauth2client). Upgrading my local httplib2 version fixed the issue.

```
$ python3 label.py ../../data/label/cat.jpg
Traceback (most recent call last):
  File "label.py", line 78, in <module>
    main(args.image_file)
  File "label.py", line 67, in main
    response = service_request.execute()
  File "/usr/local/lib/python3.4/dist-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/googleapiclient/http.py", line 755, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/usr/local/lib/python3.4/dist-packages/googleapiclient/http.py", line 93, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/oauth2client/client.py", line 622, in new_request
    redirections, connection_type)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1120, in request
    headers = self._normalize_headers(headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1088, in _normalize_headers
    return _normalize_headers(headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 194, in _normalize_headers
    return dict([ (key.lower(), NORMALIZE_SPACE.sub(value, ' ').strip())  for (key, value) in headers.items()])
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 194, in <listcomp>
    return dict([ (key.lower(), NORMALIZE_SPACE.sub(value, ' ').strip())  for (key, value) in headers.items()])
TypeError: sequence item 0: expected str instance, bytes found

$ pip3 install --upgrade google-api-python-client
Requirement already up-to-date: google-api-python-client in /usr/local/lib/python3.4/dist-packages
Cleaning up...

$ sudo pip3 install --upgrade httplib2
[sudo] password for swast: 
Downloading/unpacking httplib2 from https://pypi.python.org/packages/source/h/httplib2/httplib2-0.9.2.tar.gz#md5=bd1b1445b3b2dfa7276b09b1a07b7f0e
  Downloading httplib2-0.9.2.tar.gz (205kB): 205kB downloaded
  Running setup.py (path:/tmp/pip_build_root/httplib2/setup.py) egg_info for package httplib2

Installing collected packages: httplib2
  Found existing installation: httplib2 0.8
    Not uninstalling httplib2 at /usr/lib/python3/dist-packages, owned by OS
  Running setup.py install for httplib2

Successfully installed httplib2
Cleaning up...

$ python3 label.py ../../data/label/cat.jpg      
Found label: cat for ../../data/label/cat.jpg
```

**Comment by tswast** [comment]
@dhermes @jonparrott Please take a look.

**Comment by dhermes** [comment]
The version is required to be `>=0.9.1` [in `setup.py`][1] (that was the version that finally made Python 3 work). That's literally all we can do.

[1]: https://github.com/google/oauth2client/blob/4b0a5edd47142a02e5bf585d8009195a29036449/setup.py#L35

**Comment by jonparrott** [comment]
Seems like we should bump it to >=0.9.2 instead of >=0.9.1 ?

**Comment by dhermes** [comment]
It won't prevent whatever caused `httplib2 0.8` in the report though. It's fine with me to upgrade to the latest version, but the only difference between `0.9.1` and `0.9.2` is to "Fix incorrect ResponseNotReady exceptions, retry on transient errors." (there were also README changes between the releases).

**Comment by jonparrott** [comment]
Interesting. I'm wondering how he ended up with 0.8 in this case.

**Comment by dhermes** [comment]
I feel like `pip install` just says "meh" when already installed? Solution: always use `pip install --upgrade`.

The `google-api-python-client` [says][1] `httplib2>=0.8,<1` is cool so `--upgrade` should've given `0.9.2`?

[1]: https://github.com/google/google-api-python-client/blob/e8ed9ea1aa4e93ccef9afc8483818df43f78ddc8/setup.py#L66

**Comment by jonparrott** [comment]
But shouldn't oauth2client's requirement of >=0.9.1 have been enough for
pip to upgrade it?

**Comment by dhermes** [comment]
I don't know ¯\_(ツ)_/¯

**Comment by jonparrott** [comment]
As long as we're all on the same page. Hah.

**Comment by dhermes** [comment]
@tswast Can you reproduce this in a virtual environment? (I'm going to try too.)

**Comment by dhermes** [comment]
I went out of my way to try to make it work and it still doesn't:

```
$ virtualenv venv
$ source venv/bin/activate
(venv) $ pip freeze
wheel==0.29.0
(venv) $ pip install httplib2==0.8.0
(venv) $ pip freeze
httplib2==0.8
wheel==0.29.0
(venv) $ pip install oauth2client
(venv) $ pip freeze
httplib2==0.9.2
oauth2client==2.0.0.post1
pyasn1==0.1.9
pyasn1-modules==0.0.8
rsa==3.3
six==1.10.0
wheel==0.29.0
(venv) $ pip install --ignore-installed httplib2==0.8.0
(venv) $ pip freeze
httplib2==0.8
oauth2client==2.0.0.post1
pyasn1==0.1.9
pyasn1-modules==0.0.8
rsa==3.3
six==1.10.0
wheel==0.29.0
(venv) $ pip install --upgrade google-api-python-client
(venv) $ pip freeze
google-api-python-client==1.5.0
httplib2==0.9.2
oauth2client==2.0.0.post1
pyasn1==0.1.9
pyasn1-modules==0.0.8
rsa==3.3
simplejson==3.8.2
six==1.10.0
uritemplate==0.6
wheel==0.29.0
```

@tswast maybe you have an old version of `pip`?

**Comment by tswast** [comment]
Yeah, maybe. I'm using the one bundled with Ubuntu 14.04.

**Comment by tswast** [comment]
Hmmm... Looks like this is the same pip version within the virtualenv. I'm not sure why I can't reproduce the issue in a virtualenv.

```
$ pip --version
pip 1.5.4 from /usr/local/google/home/swast/src/vision/python/label/env/lib/python3.4/site-packages (python 3.4)
```

I'm trying to reproduce on a new GCE instance, but can't either.

```
$ sudo apt-get -qqy update
$ sudo apt-get -qqy upgrade
$ sudo apt-get -qqy install python3-pip git
$ git clone https://github.com/GoogleCloudPlatform/cloud-vision.git vision
$ cd vision/python/label

$ cat requirements.txt 
google-api-python-client>=1.3.1
$ sudo pip3 install -r requirements.txt

$ pip3 freeze
chardet==2.2.1
colorama==0.2.5
command-not-found==0.3
google-api-python-client==1.5.0
html5lib==0.999
httplib2==0.9.2
language-selector==0.1
oauth2client==2.0.0-post1
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycurl==7.19.3
pygobject==3.12.0
python-apt==0.9.3.5ubuntu2
requests==2.2.1
rsa==3.3
simplejson==3.8.2
six==1.10.0
ufw==0.34-rc-0ubuntu2
unattended-upgrades==0.1
uritemplate==0.6
urllib3==1.7.1
wheel==0.24.0
```

Maybe I just had an old version sitting around and `pip install --upgrade` decided not to update it (even though I thought that was supposed to be recursive)? Feel free to close as not reproducible.

**Comment by jonparrott** [comment]
I think we can close this one but we should bump it in google-api-python-client.
