### ISSUE TITLE
issue with installing oauth2client: "NameError: name 'sys_platform' is not defined'

### ISSUE THREAD

**Issue by zoeticclarence** [google/oauth2client#545]
I was trying to install oauth2client on my local windows machine but got the following error:
```
C:\repo\Cloud\appengine\standard\endpoints\backend>pip install --upgrade oauth2client
Collecting oauth2client
  Using cached oauth2client-2.2.0.tar.gz
Requirement already up-to-date: httplib2>=0.9.1 in c:\python27\lib\site-packages (from oauth2client)
Requirement already up-to-date: pyasn1>=0.1.7 in c:\python27\lib\site-packages (from oauth2client)
Requirement already up-to-date: pyasn1-modules>=0.0.5 in c:\python27\lib\site-packages (from oauth2client)
Requirement already up-to-date: rsa>=3.1.4 in c:\python27\lib\site-packages (from oauth2client)
Requirement already up-to-date: six>=1.6.1 in c:\python27\lib\site-packages (from oauth2client)
Building wheels for collected packages: oauth2client
  Running setup.py bdist_wheel for oauth2client ... error
  Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\clarence\\appdata\\local\\temp\\pip-build-t45sz8\\oauth2client\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d c:\users\clarence\appdata\local\temp\tmpyabjs1pip-wheel- --python-tag cp27:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "c:\users\clarence\appdata\local\temp\pip-build-t45sz8\oauth2client\setup.py", line 69, in <module>
      'Topic :: Internet :: WWW/HTTP',
    File "c:\python27\lib\distutils\core.py", line 137, in setup
      ok = dist.parse_command_line()
    File "build\bdist.win32\egg\setuptools\dist.py", line 276, in parse_command_line
    File "c:\python27\lib\distutils\dist.py", line 467, in parse_command_line
      args = self._parse_command_opts(parser, args)
    File "build\bdist.win32\egg\setuptools\dist.py", line 602, in _parse_command_opts
    File "c:\python27\lib\distutils\dist.py", line 523, in _parse_command_opts
      cmd_class = self.get_command_class(command)
    File "build\bdist.win32\egg\setuptools\dist.py", line 406, in get_command_class
    File "build\bdist.win32\egg\pkg_resources.py", line 2272, in require
    File "build\bdist.win32\egg\pkg_resources.py", line 2489, in requires
    File "build\bdist.win32\egg\pkg_resources.py", line 2700, in _dep_map
    File "build\bdist.win32\egg\pkg_resources.py", line 2733, in _compute_dependencies
    File "build\bdist.win32\egg\pkg_resources.py", line 2730, in reqs_for_extra
    File "build\bdist.win32\egg\_markerlib\markers.py", line 109, in marker_fn
    File "<environment marker>", line 1, in <module>
  NameError: name 'sys_platform' is not defined

  ----------------------------------------
  Failed building wheel for oauth2client
  Running setup.py clean for oauth2client
Failed to build oauth2client
Installing collected packages: oauth2client
  Running setup.py install for oauth2client ... done
Successfully installed oauth2client-2.2.0
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by jonparrott** [comment]
@zoeticclarence So, oauth2client *was* installed. Pip just failed to build the 'wheel' for the package.

From a cursory search, it seems like over versions of setuptools/distribute can cause this. Can you try running

```pip install --upgrade distribute```

And see if that fixes it?

**Comment by zoeticclarence** [comment]
Thanks for your help @jonparrott.

It shows:
`Requirement already up-to-date: distribute in c:\python27\lib\site-packages
Requirement already up-to-date: setuptools>=0.7 in c:\python27\lib\site-packages (from distribute)`

I think I figured out what was the issue. 
I need to run as administrator to install them.
