### ISSUE TITLE
Logs / traceback leak out from Flask unit tests

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#557]
Example:

```
py27 runtests: commands[0] | nosetests
    --ignore-files=test_appengine\.py --ignore-files=test__appengine_ndb\.py
...........................................................................
[2016-07-20 14:33:30,733] ERROR in flask_util: Invalid id_token {}
[2016-07-20 14:33:30,733] ERROR in flask_util: Invalid id_token {}
..
[2016-07-20 14:33:30,750] ERROR in flask_util: Invalid response: 500.
Traceback (most recent call last):
  File ".../oauth2client/oauth2client/contrib/flask_util.py", line 420, in callback_view
    credentials = flow.step2_exchange(code)
  File ".../oauth2client/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File ".../oauth2client/oauth2client/client.py", line 2031, in step2_exchange
    raise FlowExchangeError(error_msg)
FlowExchangeError: Invalid response: 500.
............................................................................
............................................................................
............................................................................
............................................................................
............................................................................
.......................................................................
----------------------------------------------------------------------
Ran 528 tests in 2.174s

OK
_______ summary_________
  py27: commands succeeded
  congratulations :)
```

----

Assigning to @jonparrott since he is the original implementer

**Comment by jonparrott** [comment]
I wonder if it's the test's fault or nose's fault.

**Comment by dhermes** [comment]
¯\\\_(ツ)\_/¯
